module.exports = {
    USER_PROFILE_PROJECTION: {
        email: 1,
        gender: 1,
        bodyType: 1,
        mobile: 1,
        countryCode: 1,
        countryShortCode: 1,
        dob: 1,
        anniversary: 1,
        nationality: 1,
        isProfileCompleted: 1,
        firstName: 1,
        lastName: 1,
        profileImage: 1,
        hometown: 1,
        culturalBackground: 1,
        address: 1,
        location: 1,
        dressingStyle: 1,
        occasion: 1,
        allowCommentNotification: 1,
        allowLikeNotification:1,
        deviceToken:1,
        deviceType:1
    },
    VENDOR_PROFILE_PROJECTION: {
        businessName: 1,
        mobile: 1,
        email: 1,
        businessProfileImage: 1,
        businessDescription: 1,
        businessAddress: 1,
        storeLink: 1,
        isEmailVerified: 1,
        isBlocked: 1,
        isProfileCompleted: 1,
        fbLink: 1,
        instaLink: 1,
        pinterestLink: 1,
        storeLink: 1,
        twitterLink: 1,
        countryCode:1
    }
}